# Initial cache for the ONNX-capable, CPU-only browser runtime.
# FORCE also applies these settings when reusing a build directory.
foreach(option IN ITEMS
    REDUCED_OPS_BUILD ENABLE_LTO ENABLE_WEBASSEMBLY_SIMD ENABLE_WEBASSEMBLY_THREADS
    DISABLE_RTTI DISABLE_ML_OPS DISABLE_GENERATION_OPS DISABLE_FLOAT4_TYPES
    DISABLE_FLOAT8_TYPES DISABLE_SPARSE_TENSORS DISABLE_OPTIONAL_TYPE
    DISABLE_STRING_TYPE DISABLE_EXTERNAL_INITIALIZERS)
  set(onnxruntime_${option} ON CACHE BOOL "SwiftF0 browser build" FORCE)
endforeach()

# Keep the ONNX parser and the contrib kernel the optimizer fuses into (FusedConv).
foreach(option IN ITEMS
    MINIMAL_BUILD EXTENDED_MINIMAL_BUILD DISABLE_CONTRIB_OPS DISABLE_EXCEPTIONS
    BUILD_UNIT_TESTS RUN_ONNX_TESTS BUILD_SHARED_LIB BUILD_WEBASSEMBLY_STATIC_LIB
    BUILD_CSHARP BUILD_JAVA BUILD_NODEJS BUILD_OBJC BUILD_APPLE_FRAMEWORK
    ENABLE_PYTHON ENABLE_TRAINING ENABLE_TRAINING_OPS ENABLE_TRAINING_APIS
    ENABLE_CPU_FP16_OPS USE_TELEMETRY USE_MIMALLOC USE_VCPKG
    USE_CUDA USE_TENSORRT USE_DNNL USE_OPENVINO USE_QNN USE_XNNPACK
    USE_JSEP USE_WEBGPU USE_WEBNN
    ENABLE_WEBASSEMBLY_EXCEPTION_CATCHING ENABLE_WEBASSEMBLY_API_EXCEPTION_CATCHING
    ENABLE_WEBASSEMBLY_EXCEPTION_THROWING ENABLE_WEBASSEMBLY_JSPI
    ENABLE_WEBASSEMBLY_DEBUG_INFO ENABLE_WEBASSEMBLY_PROFILING
    ENABLE_WEBASSEMBLY_RELAXED_SIMD)
  set(onnxruntime_${option} OFF CACHE BOOL "SwiftF0 browser build" FORCE)
endforeach()
set(onnxruntime_EMSCRIPTEN_SETTINGS "MALLOC=dlmalloc;STACK_SIZE=5242880"
    CACHE STRING "SwiftF0 Emscripten settings" FORCE)
